version: '3.8'

services:
  project_app:
    image: vinexborsalino/project_swarm_app:latest
    ports:
      - "9000:9000"
    environment:
      - DB_HOST=mysql_db
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=students_db
    networks:
      - students-network
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.role == worker
    depends_on:
      - mysql_db

  mysql_db:
    image: vinexborsalino/mysql_init:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: students_db
    ports:
      - "3306:3306"
    networks:
      - students-network
    deploy:
      mode: replicated
      replicas: 1  # Reduced replicas since MySQL doesn't support active-active replication
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.role == worker
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      PMA_HOST: mysql_db
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - "8080:80"
    networks:
      - students-network
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.role == worker
    depends_on:
      - mysql_db
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - students-network
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=yassine
    networks:
      - students-network

networks:
  students-network:
    driver: overlay

volumes:
  mysql_data:
    driver: local
    
   

